services:
  db_system:
    image: postgres:17-alpine
    container_name: ewallet_postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ewalletdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

  app_service:
    build: .
    container_name: ewallet_app_container
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
      - db_system
    environment:
      DB_HOST: db_system
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: ewalletdb
      SERVER_PORT: 8080
      JWT_SECRET: rahasia_super_aman_2026
      JWT_EXP: 24

volumes:
  postgres_data:
